### ISSUE TITLE
Ideas to promote the project

### ISSUE THREAD

**Issue by navendu-pottekkat** [aniketmaurya/chitra#14]
These are some ideas I have to promote this project.

We can share ideas here and grow the community around this project.

**Sharing in the following platforms**

https://news.ycombinator.com/show:

https://www.reddit.com/

https://www.producthunt.com/

https://dev.to

https://twitter.com/home

**Comment by aniketmaurya** [comment]
Yes, the project is a bit mature now and we can start sharing the idea with these platforms.

**Comment by navendu-pottekkat** [comment]
Yes, planning and sharing these during the hacktoberfest would drive more traffic to this repo and get more contributors.

**Comment by aniketmaurya** [comment]
Any suggestions for the promotion?

**Comment by navendu-pottekkat** [comment]
Yeah, I will help
