### ISSUE TITLE
ImportError: cannot import name 'show_batch' from 'chitra.dataloader'

### ISSUE THREAD

**Issue by roderick-liu** [aniketmaurya/chitra#140]
ubuntu 20.04
anconda env
install local packages
$ pip install .
Installing collected packages: chitra
  Attempting uninstall: chitra
    Found existing installation: chitra 0.2.0a1
    Uninstalling chitra-0.2.0a1:
      Successfully uninstalled chitra-0.2.0a1
Successfully installed chitra-0.2.0a1
----------------------------------------------------------
python demo.py
import numpy as np
import chitra
from chitra.dataloader import Clf, show_batch
import matplotlib.pyplot as plt
-------------------------------------------------------
 from chitra.dataloader import Clf, show_batch
ImportError: cannot import name 'show_batch' from 'chitra.dataloader'

**Comment by aniketmaurya** [comment]
hi @roderick-liu, now you can call `show_batch` method directly on the `Clf` object without the need to import that method.

```python
import numpy as np
import chitra
from chitra.dataloader import Clf
import matplotlib.pyplot as plt

clf_dl = Clf()
data = clf_dl.from_folder(cat_dog_path, target_shape=(224, 224))
clf_dl.show_batch(8, figsize=(8, 8))
```

**Comment by roderick-liu** [comment]
thank you!
