### ISSUE TITLE
Adding Support for Loading Pascal VOC dataset format to tf.data

### ISSUE THREAD

**Issue by aniketmaurya** [aniketmaurya/chitra#6]
Add a new Python module for loading Pascal VOC data format to tf.data

The function should receive an annotation and image folder path and will return the tf.Dataset object.

**Comment by mukuakhilesh** [comment]
I have used this feature to convert to tf.Record file using the API provided by tensorflow itself. In that one needs to run a python script from command line with apt arguments to get tf.Record file. 
Now, can you clarify some of my questions:

1. In tf.data you want to create same Record file or or something else ?
2. Are you trying to implement the same thing implemented in that script, in that function. Or one can find a way to use that same script file provided by tensorflow, in backend implementation of this function ?

**Comment by aniketmaurya** [comment]
> I have used this feature to convert to tf.Record file using the API provided by tensorflow itself. In that one needs to run a python script from command line with apt arguments to get tf.Record file.
> Now, can you clarify some of my questions:
> 
> 1. In tf.data you want to create same Record file or or something else ?
> 2. Are you trying to implement the same thing implemented in that script, in that function. Or one can find a way to use that same script file provided by tensorflow, in backend implementation of this function ?

I want to build a function that accepts two arguments - Pascal VOC dataset path and then loads it in tf.data  format directly (without TFRecord dataset):

```
def load_dataset(image_path, xml_path):
     # preprocess
     # convert data to tf.data
     return image_filename, image, bounding_boxes, labels
```

You can read more about [tf.data here]( https://www.tensorflow.org/guide/data#basic_mechanics)

Do let me know if you need any help.

**Comment by mukuakhilesh** [comment]
Thanks, first would like to do a bit research on this.
