### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by navendu-pottekkat** [aniketmaurya/chitra#8]
Here are some changes that I am proposing to the README to make it look better and according to the convention.

- Change the banner image to **1280x640 px** image.
- Make the headings and subheadings better.
- Add links to create an issue and contributing guide where they are mentioned in the README.
- Change "How to use section" to "Usage" as it is the convention.

You can also use the banner image as the repo preview image.

I will take this issue and make a PR.

**Comment by thesauravkarmakar** [comment]
I would like to fix this issue

**Comment by navendu-pottekkat** [comment]
fixed in pull request #9
